### PR TITLE
Just set tislack.org as long the invitation is needed for slack

### PR DESCRIPTION
**Pull request by caspahouzer**

### CODE REVIEW

**Comment by caspahouzer** [comment]
Added a project README

**Comment by cb1kenobi** [comment]
We need to hold off on this until we get the email addresses and those tidev.io pages to get created.

**Comment by caspahouzer** [comment]
> We need to hold off on this until we get the email addresses and those tidev.io pages to get created.

I think that has been resolved? @cb1kenobi

**Comment by cb1kenobi** [comment]
I have no idea why this was do not merge.

**Review by cb1kenobi — APPROVED** [review]
**APPROVED**

**Pull request merged**
